### ISSUE TITLE
"Could not read signing key" and Internal Server Error when generating pass

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [pretix/pretix-passbook#62]
Both pretix and the plugin are the latest version. I have configured the keys and certificates in the settings. When a pass is generated, an Internal Server Error is thrown and the following is written to the logfile:

```
ERROR 2024-03-08 21:31:57,898 django.request log Internal Server Error: /control/event/events/2024/settings/tickets/preview/passbook
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pretix/src/pretix/control/permissions.py", line 69, in wrapper
    return function(request, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pretix/src/pretix/control/views/event.py", line 829, in get
    fname, mimet, data = tickets.preview(self.request.event.pk, self.output.identifier)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pretix/src/pretix/base/services/tickets.py", line 123, in preview
    return prov.generate(p)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pretix_passbook/passbook.py", line 571, in generate
    _pass = passfile.create(
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wallet/models.py", line 302, in create
    signature = self._createSignature(manifest, certificate, key, wwdr_certificate, password)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wallet/models.py", line 347, in _createSignature
    raise Exception(error)
Exception: b'Could not read signing key from /tmp/tmpwmg6cdcv\n'
```

Not sure even where to start with this, any help would be appreciated! Let me know if you need any more information.

**Comment by raphaelm** [comment]
Have not seen this before, sorry. Looks like an invalid signing key, though.

**Comment by BlueHairMinerBoy** [comment]
I ended up re creating all the keys and it works now
